### ISSUE TITLE
Sum statistics are not correct visualized on edges.

### ISSUE THREAD

**Issue by mariusoe** [NovatecConsulting/novatec-service-dependency-graph-panel#14]
When using the "Handle Timings as Sum" option, only the statistics shown at the nodes are correclty calculated. The statistics shown on the edges are not considered as sum statistics which causes huge numbers of wrong statistics.

**Comment by JonasKunz** [comment]
This also applies to the numbers shown in the statistics table

**Comment by mariusoe** [comment]
Fixed by #16
