### ISSUE TITLE
Zooming with Shift+MouseWheel in Service Graph is not working

### ISSUE THREAD

**Issue by Well5a** [NovatecConsulting/novatec-service-dependency-graph-panel#2]
This feature is described in the Readme: "You can zoom in and out of the SDG by using the mouse wheel while the SHIFT key is pressed.". However this seems not to be implemented or working correctly. The buttons for zooming in and out are working as intended.

**Comment by mc-chaos** [comment]
With the New release this is Working. Pls test again.

**Comment by mariusoe** [comment]
Yes, this issue has been fixed in the latest version due to a replacement of the visualization framework.
