### ISSUE TITLE
Difference between the requests count of a service and its dependencies

### ISSUE THREAD

**Issue by Well5a** [NovatecConsulting/novatec-service-dependency-graph-panel#3]
### My setup:
I am running an app in a Kubernetes cluster. I am using the default service graph panel from [here](https://github.com/inspectIT/inspectit-ocelot/blob/master/inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/service-graph.json).

### The problem:
The requests count of the discovery server service is higher than the sum of the requests on the dependencies leading to the service. The picture below shows a difference of 92-86=6 requests: 
![discovery](https://user-images.githubusercontent.com/28290219/57529539-77b01480-7335-11e9-8a1c-7168806eacd5.PNG)
The difference stays the same no matter how the count values are changing.
The same happens with the requests count of the database (43-39=4):
![database](https://user-images.githubusercontent.com/28290219/57529718-e4c3aa00-7335-11e9-9d9c-43d588668ccf.PNG)

I can't tell where the additional requests are coming from.

**Comment by mariusoe** [comment]
This issue should be resolved when using the latest version due to a big amount of bug fixes. Please try the latest version and feel free to reopen this issue if it is still not correct
