### ISSUE TITLE
Prometheus data source

### ISSUE THREAD

**Issue by xkilian** [NovatecConsulting/novatec-service-dependency-graph-panel#33]
Any chance to make this plugin compatible with the Prometheus data source?

**Comment by AlexanderWert** [comment]
Hi @xkilian,
actually this plugin is already compatible with the Prometheus datasource! 
Here is an example of a corresponding dashboard with Prometheus as datasource:

https://github.com/inspectIT/inspectit-ocelot/blob/master/inspectit-ocelot-demo/grafana/provisioning/prometheus/dashboards/service-graph.json

**Comment by xkilian** [comment]
Thank you for the example, I will test it out with my datasource.

**Comment by mariomann** [comment]
closed.
