### ISSUE TITLE
icom mapping

### ISSUE THREAD

**Issue by liuxi653** [NovatecConsulting/novatec-service-dependency-graph-panel#36]
![image](https://user-images.githubusercontent.com/37133475/94523638-10fe0480-0264-11eb-8903-eb5bfcc590de.png)
![image](https://user-images.githubusercontent.com/37133475/94523657-1b200300-0264-11eb-92c6-520750383349.png)
how to config to show the icon

**Comment by mbrill-nt** [comment]
Hi @liuxi653 ,

**Comment by mbrill-nt** [comment]
Hi @liuxi653 , sorry for the late reply! <br/> To use the custom icon mapping, you first need to provide the name of the column where the target-type for each dataset is defined. To do so, enter the name of the column in the "Type"-Field: 
![Capture](https://user-images.githubusercontent.com/53812669/96261015-1ecfbb80-0fc0-11eb-97d5-09f0b960e530.PNG)  <br/> From here on, you only need to provide the respective type in the column you have added. (e.g. `source_event` should contain `web` for your java3-dataset). <br/>
