### ISSUE TITLE
TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by nullbodysoft** [NovatecConsulting/novatec-service-dependency-graph-panel#37]
TypeError: Cannot read property 'emit' of undefined

i got error when build these plugin via yarn build

on grafana 7.2.0

An unexpected error happened
Details
TypeError: Cannot read property 'emit' of undefined

    in t
    in x
    in to
    in div
    in div
    in t
    in t
    in div
    in Mo
    in div
    in div
    in vo
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

**Comment by mariomann** [comment]
Hi @nullbodysoft, sorry for the late response.
I've checked the built version of this repo with Grafana 7.2.0 and it works as desired.

Maybe you need to validate your local development setup or just use the built version of this repo.

Hope to help you with this answer.

Cheers
Mario

**Comment by mariomann** [comment]
I forget the screenshot...

![Issue38](https://user-images.githubusercontent.com/3458678/96266181-a4566a00-0fc6-11eb-8ff0-d41fb190d255.png)
