### ISSUE TITLE
[Question] - How to initial template variable

### ISSUE THREAD

**Issue by mnstr99** [NovatecConsulting/novatec-service-dependency-graph-panel#39]
i've initialized the variable with template type = "constant", and also define value as "app" follows the sample but the graph panel still shows as "Please provide a 'aggregationType' template variable."

can you please suggest if additional configure is required?

**Screenshots
![image](https://user-images.githubusercontent.com/20295485/96828702-51673180-1462-11eb-8790-3c1121c08d6c.png)
**

**Where and how could we improve the readme?**

**Comment by mbrill-nt** [comment]
Hi @mnstr99, set the "Type" field in the variable edit window to "Custom" and the "Hide" field to "Variable" and check if that works. 
![Capture](https://user-images.githubusercontent.com/53812669/96849558-0b0bd580-1456-11eb-9696-21006919a532.PNG)

**Comment by mnstr99** [comment]
it's resolved by just save the dashboard (i didn't at the first place)

thanks @mbrill-nt
