### ISSUE TITLE
Can't create 2 graphs

### ISSUE THREAD

**Issue by rafal-dudek** [NovatecConsulting/novatec-service-dependency-graph-panel#5]
I created 2 graphs using novatec-service-dependency-graph-panel.
After saving and opening the dashboard, second graph stoped working.

Both graphs are identical, but second displays empty tile. When using +/- on the second graph, the first is zooming too.

![graph](https://user-images.githubusercontent.com/32459286/60260798-a92b7200-98da-11e9-8b73-272b8719d077.PNG)

**Comment by AlexanderWert** [comment]
Thanks @rafal-dudek , we will have a look into this issue!

**Comment by mariusoe** [comment]
This issue has been fixed in the latest release v2. You should be able to create two separate service graph panels on the same dashboard, now.
