### ISSUE TITLE
[Info] - *DataV  is using SDG*

### ISSUE THREAD

**Issue by mc-chaos** [NovatecConsulting/novatec-service-dependency-graph-panel#50]
The datav.dev Projekt (grafana fork) shows the SDG on its example screenshots
https://github.com/opendatav/datav

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8655273/101983929-42d91180-3c7e-11eb-805b-0ebfc05047b1.png)

**Comment by sunface** [comment]
yes, we include this plugin as our core plugin for **service dependency**, very nice plugin, thank you :)

**Comment by mc-chaos** [comment]
@sunface : Thx for your feedback. 
@mariusoe :Thing we need a "Adopters.md" File.

I am interested to exchange some about the Usage of SDG. We are a big User of the inspect-IT Stage ( https://github.com/inspectIT/inspectit-ocelot ) and use the SDG as our Main Service overview.

Are you interested in personal contact? Mail / IM ?

**Comment by mc-chaos** [comment]
@mariomann @mariusoe : Here is the URL to the Version from SDG used by DataV. Looks liken, the have done most of the Rework for us.
https://github.com/opendatav/datav/tree/master/ui/src/plugins/built-in/panel/dependency-graph

**Comment by mariomann** [comment]
Hi @mc-chaos,

thx for the really interesting information about the datav project. And it's also nice to read that this plugin is a core plugin in this project.

> @mariusoe :Thing we need a "Adopters.md" File.
I don't know what you understand in an adopters.md file or what you think is a benefit about this. But this is an open source project, so please feel free to create such a file and open a pull request. Than we can discuss in more details about this idea.

Thank you.

**Comment by mariomann** [comment]
> @mariomann @mariusoe : Here is the URL to the Version from SDG used by DataV. Looks liken, the have done most of the Rework for us.
> https://github.com/opendatav/datav/tree/master/ui/src/plugins/built-in/panel/dependency-graph

Hi @mc-chaos,

thx for pointing the copied code for us. Last week we also had a look in this source code. This source code is quite good but does not suit or development requirements we have. Currently we develop a new version of this plugin based on react framework and we plan to release this in first quarter in 2021.

Hope to help you with this information.

**Comment by sunface** [comment]
Hi, @mc-chaos, @mariomann
I have already added **Novatec** as the author to the plugin in datav,  if you released a new version in react, I will update to the newest version.

**Comment by mc-chaos** [comment]
Only information.
