### ISSUE TITLE
[Feature] - Make headers sortable in incoming/outgoing statistics

### ISSUE THREAD

**Issue by vmanju123** [NovatecConsulting/novatec-service-dependency-graph-panel#57]
![image](https://user-images.githubusercontent.com/61594112/103031915-ca4f3c00-452c-11eb-9f00-80d0dd346bfd.png)

**Comment by MariusBrill** [comment]
Hey, @vmanju123 

as for now, there is no functionality to do so. We will however add your issue as a feature request. 

Greetins
Marius

**Comment by MariusBrill** [comment]
Hey, @vmanju123 

as for now, there is no functionality to do so. We will however add your issue as a feature request. 

Greetings
Marius

**Comment by MariusBrill** [comment]
Hi @vmanju123 ,

The feature is available in our new release 4.0.0
It should also soon be available on grafana.

Greetings
Marius
