### ISSUE TITLE
[Feature] - Change unit type for data

### ISSUE THREAD

**Issue by maemigh** [NovatecConsulting/novatec-service-dependency-graph-panel#59]
**Is your feature request related to a problem? Please describe.**
It seems that response time is hardcoded to be ms. I'm making a graph where seconds would be more appropriate.

**Describe the solution you'd like**
Option to choose unit type. Even if multiplying the seconds value by 1000, it defaults to minutes. In our case, I think it's more preferable to show something like 90 sec rather than 1.5 min.

**Comment by MariusBrill** [comment]
Hi @maemigh, 

Thank you for the feature request!
We are currently implementing it and i will get back to you as soon as it is finished.

Cheers
Marius

**Comment by MariusBrill** [comment]
Hi @maemigh,

the feature is added to our newly released version 4.0.0.
It should also soon be published on Grafana.

Greetings
Marius

**Comment by maemigh** [comment]
@MariusBrill Hello, I wonder if something was missed for it to be published or if it's just awaiting on the grafana team?

**Comment by MariusBrill** [comment]
Hi @maemigh ,

Yes, we are currently waiting for the grafana team to publish our new release to the marketplace.
However you can already use the latest version by downloading our [latest release](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases/tag/v4.0.0) and unzipping the `novatec-sdg-panel.zip` file into the `panels`-folder of your grafana installation.

Greetings
Marius
