### ISSUE TITLE
Can you publish to Grafana.com please?

### ISSUE THREAD

**Issue by bhozar** [NovatecConsulting/novatec-service-dependency-graph-panel#6]
Is it possible to get this pubished to Grafana.com please? Would make it a lot easier to install and update and will increase the audience for the plugin as it looks really good.

**Comment by mariomann** [comment]
Hi @bhozar,

the panel is published on [grafana.com](https://grafana.com/grafana/plugins/novatec-sdg-panel), now.

This ticket will be closed.
