### ISSUE TITLE
[Question] - I can't get the data properly, I don't know where the problem is.*

### ISSUE THREAD

**Issue by qicaihuoyan** [NovatecConsulting/novatec-service-dependency-graph-panel#65]
The data source is influxdb1.8.3
grafana is Latest Version

![截屏2021-02-09 13 08 13](https://user-images.githubusercontent.com/13148034/107318506-e2c4e700-6ad7-11eb-9cb3-f4fa8c84eb73.png)

![截屏2021-02-09 13 08 35](https://user-images.githubusercontent.com/13148034/107318529-eeb0a900-6ad7-11eb-92dd-36b0d2c41bc5.png)

Where is the problem with my settings please ask

**Comment by MariusBrill** [comment]
Hi @qicaihuoyan ,

It seems like you don't query your source_app and target_app fields with your influx query. You can check this by clicking "Query Inspector" -> "Data". If there is no Data dsiplayed there must be some issue with your query.

Greetings
Marius

**Comment by qicaihuoyan** [comment]
> It seems like you don't query your source_app and target_app fields with your influx query. You can check this by clicking "Query Inspector" -> "Data". If there is no Data dsiplayed there must be some issue with your query.

![image](https://user-images.githubusercontent.com/13148034/108300513-68811a80-71db-11eb-9d09-e5687a0e4ba1.png)

I can't query field is source_app and target_app, because their type is not string, I can only query req_rate, it has return data
But the "relationship map" still does not appear

![image](https://user-images.githubusercontent.com/13148034/108300746-dcbbbe00-71db-11eb-911c-5efaa2b8a266.png)
![image](https://user-images.githubusercontent.com/13148034/108300759-e0e7db80-71db-11eb-84b6-5fefecf8ace9.png)

**Comment by qicaihuoyan** [comment]
Is it related to my grafana version is the latest version, I see wiki write 4.0 only support 7.1

**Comment by qicaihuoyan** [comment]
Resolved
