### ISSUE TITLE
Data is not displayed

### ISSUE THREAD

**Issue by temabeloglinskiy** [NovatecConsulting/novatec-service-dependency-graph-panel#71]
I have a data display problem. I'm created a separate table as in the example, but I don't see the data in the dashboard.

Please help solve the problem.

![image](https://user-images.githubusercontent.com/80000094/109854760-79fd0480-7c68-11eb-88cd-cc8881e09cfc.png)
![image](https://user-images.githubusercontent.com/80000094/109854869-9d27b400-7c68-11eb-91f6-6c13cfa6f39e.png)
![image](https://user-images.githubusercontent.com/80000094/109854965-c1839080-7c68-11eb-9bd9-eabdb3a31c0a.png)

**Comment by MariusBrill** [comment]
Hi @temabeloglinskiy,
it looks like you are using the version from the grafana martketplace, which is outdated. In this version, you need to provide a template variable called `aggregationType` in which you need to add the name of your service-field (in your case `app`).
You can then leave the field `Source Component Prefix` blank and just add `target_` as your 'Target Component Column Prefix'. 

However, if you want to use the latest version of our panel you can use out [latest release](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases), which does not use the variable `aggregationType` anymore.

Greetings
Marius

**Comment by stefanvozd** [comment]
I tried using versions 4.0.0 and 4.0.2 from release page, but I still get `Please provide a 'aggregationType' template variable.`

**Comment by MariusBrill** [comment]
Hi @stefanvozd 

This appears to be an unrelated issue. Could you please open a new issue for this? Also please append a screenshot of the message and your panel options.

Greetings
Marius

**Comment by temabeloglinskiy** [comment]
Hi all. I solved the problem by reinstalling the plugin. 

Thanks a lot.
