### ISSUE TITLE
[BUG] - All Node Names (Labels) of Nodes Not Seen Simultaneously In the Service Dependency Graph.

### ISSUE THREAD

**Issue by Mahi1704** [NovatecConsulting/novatec-service-dependency-graph-panel#74]
Describe the bug - 
The names of the nodes and it's details are not getting displayed in the graph without clicking on the nodes.
I chose visualisation as "Service Dependency Graph". Screenshot of the graph with only dots (nodes) and no description is attached here. I can see the tabular data in my query inspector data. I want node names to be seen simultaneously for all the nodes. Right now I have to click on individual nodes one by one to see the node name and description of the node (only that node is seen, on at a time.)

To Reproduce - The Query Inspector Data (my table) is attached here to reproduce this scenario.
Please provide as much and as detailed information as possible as it will make it easier for us to reproduce and fix the bug!

Expected behavior -
All node names should appear when the graph is generated. Instead we have to click on each node to see the name and description of node which is not the expected behaviour. Screenshot of expected behaviour is attached here.

Screenshots -
The graph with only dots (nodes) and no description.
<img width="763" alt="GraphWithNoNodeName" src="https://user-images.githubusercontent.com/28889831/110286657-4d9c0c00-800b-11eb-9273-88cc6f7376a6.png">

The Query Inspector Data (my table)
<img width="1418" alt="TableData" src="https://user-images.githubusercontent.com/28889831/110286640-483ec180-800b-11eb-9e47-ce0e7e2341a0.png">
[DepedencyGraphTable.xlsx](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/files/6099532/DepedencyGraphTable.xlsx)

Expected behavioural Dependency graph with node names.
<img width="1024" alt="ExpectedGraph" src="https://user-images.githubusercontent.com/28889831/110286663-4ffe6600-800b-11eb-941e-57bda5c8c74d.png">

Your Setup:
OS: Mac OS
Browser : Chrome
Grafana-Version : 7.2.1
Plugin : Service Dependency Graph Visualisation

Please help me with this issue.

**Comment by MariusBrill** [comment]
Hi @Mahi1704 ,

Could you please try and zoom into the panel and check if the labels appear? The labels disappear if the panel is zoomed out to a specific extend.

If this does not work, could you please send a screenshot of your panel options and a screenshot of the console of your browsers dev tools?

Greetings
Marius

**Comment by Mahi1704** [comment]
Hi @MariusBrill 
I tried zooming in and out both to their maximum extent. At no point labels started to appear. The white dots in the edges move in the direction of source to destination, but when I zoom out max then the stop moving and the graph freezes.
Switching browsers also didn't help. It is same for others in my team too.
Attached here is the screenshot of my panel option and console of browsers dev tools.

<img width="1792" alt="Screen Shot 2021-03-08 at 6 37 32 PM" src="https://user-images.githubusercontent.com/28889831/110325687-a5536b00-803d-11eb-80a5-0184c2085de1.png">
<img width="1792" alt="Screen Shot 2021-03-08 at 6 38 12 PM" src="https://user-images.githubusercontent.com/28889831/110325688-a5536b00-803d-11eb-8e6f-bc6f4ff4746f.png">
<img width="1786" alt="Screen Shot 2021-03-08 at 6 29 15 PM" src="https://user-images.githubusercontent.com/28889831/110325715-ac7a7900-803d-11eb-95db-e3c548e12f82.png">

**Comment by MariusBrill** [comment]
Hi @Mahi1704 

Unfortunately i am not able to reproduce the bug. Could you try to check if the issue also appears with the panel's dummy data?

Otherwise i would advise you to update to the latest [version 4.0.2](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases/tag/v4.0.2) and see if the error persists.

Greetings 
Marius

**Comment by Mahi1704** [comment]
@MariusBrill the issue does not appear with dummy data. Ok sure, I will update the version and try.
<img width="1226" alt="Screen Shot 2021-03-08 at 9 48 41 PM" src="https://user-images.githubusercontent.com/28889831/110348965-37686d00-8058-11eb-82cf-b976bc1b640a.png">

**Comment by Mahi1704** [comment]
@MariusBrill could you pls confirm that the labels should actually appear with version 2.3.0 too and also that my table data and panel settings are all correct? Because for dummy data I can see that zooming in works to bring the labels.

**Comment by MariusBrill** [comment]
HI @Mahi1704 ,

You find the default json in this [panel.zip](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/files/6128337/panel.zip).

Greetings
Marius

**Comment by emma-luk** [comment]
Dear @Mahi1704 @MariusBrill 

I just started using the novatec service dependency graph panel.

Could you please help me the following questions?
How can I import the dummy data to the service dependency graph?
How to use data sources to the service dependency graph in Grafana?

Thanks
