### ISSUE TITLE
[Question] - "No data to show" when trying out the sample

### ISSUE THREAD

**Issue by Vijay-Nirmal** [NovatecConsulting/novatec-service-dependency-graph-panel#80]
**Write your question here**

I am trying out the [Example 1](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel#example-1) provided in the docs. I am getting `No data to show - the query returned no data` error. I think this is a mistake from my part rather than a bug, so I raised this issue as question.

**Steps I followed**

Below steps are done in latest version in Grafana Plugin website (2.3.0)

1. Set data source as `Azure Data Explorer Datasource` using [there plugin](https://grafana.com/grafana/plugins/grafana-azure-data-explorer-datasource/), since I have to get actual data from ADX.
2. Used KQL to create the Example table in Grafana. Its creating proper table when using `Table` visualization.
    ```kql
    let T = datatable(app:string, target_app:string, req_rate:int)
    [
       "service a", "service b", 50,
       "service a", "service c", 75,
       "service c", "service d", 25,
    ];
    T
    ```
    ![image](https://user-images.githubusercontent.com/24755596/113835267-73066c00-97a9-11eb-8ce8-ac20350ac7b2.png)
3. Set visualization to Service Dependency Graph and set the following values
    - `Target Component Column Prefix` as `target_`
    - `Request Rate Column` as `req_rate`
    -  Create a new variable for dashboard and name it as `aggregationType` with type as constant and value as `app`
        ![image](https://user-images.githubusercontent.com/24755596/113832654-70eede00-97a6-11eb-80e9-d7938ab6f018.png)
4. After I give `Run Query`, it shows `No data to show - the query returned no data` error
    ![image](https://user-images.githubusercontent.com/24755596/113832569-5caae100-97a6-11eb-8326-2b54f11f2455.png)

**Your Setup:**

- OS Grafana is running on: Windows
- OS & Browser from which Grafana is accessed: Chrome
- Plugin-Version: 2.3.0 (Small question, why the latest release in Github shows 4.0.2 but in Grafana Plugin website it shows 2.3.0)
- Grafana-Version: Grafana v7.5.2
- Datasource & Version: Azure Data Explorer Datasource

**Comment by MariusBrill** [comment]
Hi @Vijay-Nirmal ,

could you check in the query inspector if the data arrives correctly in grafana? You can see [here](https://community.grafana.com/t/using-grafanas-query-inspector-to-troubleshoot-issues/2630) how it works.

Greetings
Marius

**Comment by Vijay-Nirmal** [comment]
When I use the latest version from the GitHub release it worked fine so I will close this issue. Anyway, thanks for the help and the wonderful plugin.
