### ISSUE TITLE
Can we call an API in the backend every time we load/refresh the dashboard ?

### ISSUE THREAD

**Issue by kbiyani33** [NovatecConsulting/novatec-service-dependency-graph-panel#84]
**Is that is there any way to call an API in the backend while loading/reloading the Service Dependancy Graph (SDG) Plugin ?**

So we are working on a small solution project that involves developing a configuration of data flow within our system. We wished to use the plugin for dynamically putting up the SDG based on data from influx database. 

But what we want is for us to be able to call an API in the backend at every reload/refresh of the dashboard page, so that if there's any change in the data flow configuration, the API will push the data to influx and we could fetch the latest configuration from there.

**So our main question **

I don't have any screenshots as of now. But if you think there's no such feature as of now, I'd be willing to raise a feature request if you guys are having the time to do the same.

**Comment by MariusBrill** [comment]
Hi @kbiyani33 ,

Sorry for the late reply! 
Thank you very much for your interest for this project, we are always happy to get new ideas! As for now there is no such feature yet, so feel free create a feature request!

Greetings
Marius

**Comment by kbiyani33** [comment]
Hi @MariusBrill 
No problem, so we found a way to edit the code to satisfy our requirement. Thanks for your response.
