### ISSUE TITLE
[Question] - Graph is blank

### ISSUE THREAD

**Issue by CrashLaker** [NovatecConsulting/novatec-service-dependency-graph-panel#85]
Hi all,

I just started using this plugin.
I'm trying to setup a vis but it's not rendering.
Can anyone help me?

my `aggregationType` is set to `app`.

my datatable is shown as this:

![image](https://user-images.githubusercontent.com/4432491/117355157-91cf4f80-ae88-11eb-8845-805dc039cadf.png)

when switching to service map nothing is shown

![image](https://user-images.githubusercontent.com/4432491/117355223-add2f100-ae88-11eb-8b31-c4bc5b8031f0.png)

**Comment by CrashLaker** [comment]
Ok so trying with readme's example.

![image](https://user-images.githubusercontent.com/4432491/117357712-a82ada80-ae8b-11eb-8f4c-05a4622f1ec0.png)

![image](https://user-images.githubusercontent.com/4432491/117358004-00fa7300-ae8c-11eb-967d-fc5901875e7f.png)

![image](https://user-images.githubusercontent.com/4432491/117357929-ecb67600-ae8b-11eb-907e-8a3a7a77bcb3.png)

![image](https://user-images.githubusercontent.com/4432491/117357686-a19c6300-ae8b-11eb-8d82-900dc985b27f.png)

**Comment by CrashLaker** [comment]
it's working now.
but this is strange i could only make it work by setting `app` as `target` and `origin_app` as `source`.
if i set `Target Component Column` to `target_app` it breaks.
can i just ignore this option?

table
![image](https://user-images.githubusercontent.com/4432491/117362704-f93dcd00-ae91-11eb-9bb6-6ab67bfd0ff9.png)

working
![image](https://user-images.githubusercontent.com/4432491/117362537-c4317a80-ae91-11eb-884c-a4e0ea7f2e00.png)

broke

![image](https://user-images.githubusercontent.com/4432491/117362589-d14e6980-ae91-11eb-952f-c1186e8f3b3c.png)

**Comment by CrashLaker** [comment]
Am i missing some config or I can only tag an icon by its name?

`Target Name (RegEx)`

![image](https://user-images.githubusercontent.com/4432491/117365721-196f8b00-ae96-11eb-900a-9e812280898f.png)

**Comment by emma-luk** [comment]
> Hi all,
> 
> I just started using this plugin.
> I'm trying to setup a vis but it's not rendering.
> Can anyone help me?
> 
> my `aggregationType` is set to `app`.
> 
> my datatable is shown as this:
> 
> ![image](https://user-images.githubusercontent.com/4432491/117355157-91cf4f80-ae88-11eb-8845-805dc039cadf.png)
> 
> when switching to service map nothing is shown
> 
> ![image](https://user-images.githubusercontent.com/4432491/117355223-add2f100-ae88-11eb-8b31-c4bc5b8031f0.png)
@CrashLaker 
I just started using the novatec service dependency graph panel.

Could you please help me with the following questions?
How can I import the dummy data to the service dependency graph?
How to use data sources to the service dependency graph in Grafana?

**Comment by CrashLaker** [comment]
Hi @emma-luk 
You mean to show "Dummy Data"?
Check if your Dummy Data switch is on.
![image](https://user-images.githubusercontent.com/4432491/117673701-63e85480-b181-11eb-8166-0defa75093f1.png)

The only problem is that I think this version lost icon mapping by an specific column.
Now only names are supported `Target Name (RegEx)`

![image](https://user-images.githubusercontent.com/4432491/117673924-a1e57880-b181-11eb-8f80-06b06722f49b.png)

**Comment by emma-luk** [comment]
> Hi @emma-luk
> You mean to show "Dummy Data"?
> Check if your Dummy Data switch is on.
> ![image](https://user-images.githubusercontent.com/4432491/117673701-63e85480-b181-11eb-8166-0defa75093f1.png)
> 
> The only problem is that I think this version lost icon mapping by an specific column.
> Now only names are supported `Target Name (RegEx)`
> 
> ![image](https://user-images.githubusercontent.com/4432491/117673924-a1e57880-b181-11eb-8f80-06b06722f49b.png)

Hi @CrashLaker 
I don't have data.
Do I need to upload Dummy Data first then show "Dummy Data"?

![image](https://user-images.githubusercontent.com/15717243/117677735-a2dcd100-b1a6-11eb-8956-57b99609ee0e.png)

thanks

Emma

**Comment by emma-luk** [comment]
> Hi @emma-luk
> 
> You don't need to upload any data to use `Dummy Data` the data is already there [hardcoded](https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/blob/master/src/dummy_data_frame.ts)
> 
> Your problem is that you need to setup an 'aggregationType' variable.
> 
> You have 2 options:
> 
> 1. create the variable
> 2. use a newer version
> 
> the plugin version above 4.0.0 doesn't require that anymore
> ![image](https://user-images.githubusercontent.com/4432491/117681076-1de2bf00-b188-11eb-9cd0-91430069ca93.png)
> 
> https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/releases

@CrashLaker Thank you

**Comment by emma-luk** [comment]
@CrashLaker 

I used InfluxDB, error: Invalid query types - only use queries which return table data. How do you insert data? I will use my own data source?

![image](https://user-images.githubusercontent.com/15717243/117993331-8ae88700-b337-11eb-8388-1269853b8d38.png)

**Comment by CrashLaker** [comment]
@emma-luk 

I see you're using `aggregationType = service`
when you switch to `Table` visualization make sure it shows at least 2 columns: `origin_service` and `service`
or whatever you've inserted in `Source Component Column Prefix = origin_`
like the first image of this issue

**Comment by emma-luk** [comment]
@CrashLaker 

Thank you for your help.

Could you please take a look at this bug at https://github.com/NovatecConsulting/novatec-service-dependency-graph-panel/issues/87 Why does my screen freeze zoom in (Chrome version 83.0.4103.61 (Official Build) (64-bit)

**Comment by MariusBrill** [comment]
Hi @CrashLaker,
Sorry for the late repy!

> Am i missing some config or I can only tag an icon by its name?
> 
> `Target Name (RegEx)`
> 
> ![image](https://user-images.githubusercontent.com/4432491/117365721-196f8b00-ae96-11eb-900a-9e812280898f.png)

In case you have not found a solution yet:
The Target Name is interpreted as a RegEx. This RegEx-Pattern then matches for all internal node-names.
The External Icon Mapping however matches by the given type.

So as for now you can only match by name. If you have other ideas how the matching could be enhanced, you are very welcome to create a feature request!

Greetings
Marius
