### ISSUE TITLE
[Question] - Grafana error says "panel plugin not found" after installs the Service Dependency Graph plugin

### ISSUE THREAD

**Issue by AmilaDevops** [NovatecConsulting/novatec-service-dependency-graph-panel#89]
**I installed Service Dependency Graph plugin in my **Grafana (v7.5.5)** and I installed the plugin from here _https://grafana.com/grafana/plugins/novatec-sdg-panel/_.  I successfully installed the plugin in grafana and restarted the grafana service but when I try to upload the **custom dashboard** into grafana _https://grafana.com/grafana/dashboards/10142_  , but after I load the dashboard below error displays on grafana dashboard when I view it**

**![image](https://user-images.githubusercontent.com/44959238/122326821-81f86000-cf4a-11eb-82ec-e7f00c5d4282.png)**

Could anyone help me out ? why the dashboard panel says "Panel plugin not found: novatec-service-dependency-graph-panel", even if I have installed the grfana plugin ?  

@MariusBrill 
Thanks

**Comment by AmilaDevops** [comment]
@MariusBrill ,  did you guys have same kind of experience before ?

**Comment by mc-chaos** [comment]
Hi @AmilaDevops , the Plugin has a new name. If nobody updatet the example dashboards, you need to change the Name.  The Panel has now the name "novatec-sdg-panel". Before release 3.0.0 it was named "novatec-service-dependency-graph-panel". Look at the releasenotes for v 3.0.0. Oben the Panel-Config und search for "novatec-service-dependency-graph-panel" in the JSON and replace it with "novatec-sdg-panel".
Regards, Sascha

**Comment by mc-chaos** [comment]
@mariusoe : You should update the example dashboards for the new SDG version.

**Comment by AmilaDevops** [comment]
Thanks for your comment @mc-chaos  I have changed the name in the json and now I don't get the previous error. 

But now after load the dashboard getting this error message,   
![image](https://user-images.githubusercontent.com/44959238/122351040-618ccd80-cf6b-11eb-8ed8-61f018ede794.png)

fyi - I'm having InfluxDB data source for my dashboard which contains SNMP data from LibreNMS

**Comment by mc-chaos** [comment]
Do you have the right datasource and RP configured? Looks like, the Dashboard is not finding your InfluxDB.
With version of InfluxDB do you have? As far as i know, only v1.x is tested.
Regards, Sascha

**Comment by mc-chaos** [comment]
Cool idee to use SNMP Network data for this dashboard. If you have this up and running, i am interested  in this solution. 
Regards, Sascha

**Comment by AmilaDevops** [comment]
I will let you know the InfluxDB version soon @mc-chaos,      But what did you mean by **RP configured**?

Also below is when I go to Panel Service Graph > edit    looks like 
![image](https://user-images.githubusercontent.com/44959238/122368826-4b870900-cf7b-11eb-81fc-a9a86029c190.png)

**Comment by mc-chaos** [comment]
Hi @AmilaDevops , this looks like InfluxDB 1.x . InfluxDB 1.x uses Databases an Retention Policy as "StoragePool". Looks like, you have defined some default Retention Policy (-> FROM "autogen"; here is autogen your selected RP). We have named our RPs with different names, so could be that is on your site?
Think of "rp" as "Table" on a Database. if you select the wrong table, you will get an error.
Did you have checked in Grafana-Explorer if you could select/see some date with this search?
I always use the Explorer to look at the RAW data as first step. So i could see, if there are Data an with are the Fieldnames are.

**Comment by AmilaDevops** [comment]
hi @mc-chaos yes you were right my InfluxDB retention policy is  "cleanup" not "autogen",  then after I changed it to  "cleanup" no any error message but no any out put either.  So do you think I should query the tables which exist SNMP data ?  other than I query the retention policy table ?    

 I'm not an expert in InfluxDB table structure, I just want to query the SNMP data and get some output which I has inside the InfluxDB.

**Comment by AmilaDevops** [comment]
also @mc-chaos  my InfluxDB version is 1.6.4,   do you guys have any idea why I don't get any output when I query even the correct rp ?

**Comment by AmilaDevops** [comment]
hi @mc-chaos  I still have this error with Grfana datasource
![image](https://user-images.githubusercontent.com/44959238/122913586-40671b00-d377-11eb-929c-cf16b32af9ad.png)

even after I changed RP it gives no out put 
![image](https://user-images.githubusercontent.com/44959238/122913752-786e5e00-d377-11eb-9768-93b5285f371c.png)


@mc-chaos  and @emma-luk **actually I want something to show in my dashboard but still I see nothing**,  can you guys at lease tell me is it my InfluxDB issue or Grafana dashboard settings issue with your plugin ?

**Comment by mc-chaos** [comment]
@AmilaDevops  Do you have searched in Grafana-Explorer if there is Data in your Datasource? Are you using the right Metrics and TAGs? 
As i say a few days ago, have you used your query in the Grafana-Explorer or influx Chronograf to check that you selected the right metrics and tags? Are the Variable "service" filled in Grafana? With the right data? Are the fields and TAGs you are selecting exists in the Datasource( count; service_in_responsetime; service; orgin_service; target_external; protocol ? "cleanup" is an exotic name for RP. Are you using the right RP? We have our RP named "raw" and "rp5m" and "rp1h" for different aggregation. could it be, that you are using a "cleanup/delete" RP?
First you should be able to see some data in Grafana-Explorer and than you should use some complex Dashboards, with needs some experiences with influxDB/Grafana.
This is an opensource Project. I am an User of this project. I am not an Creator or Support-Agent of this opensource project. If you have a technical problem, get a (payed) support-contract from the company "novatec" and they will help you. I will help you,if i could, but do not think i am your support-agent.
regards, Sascha
